version: '3'

services:
    api:
        build: ./api
        container_name: fossil-jackets-api
        depends_on:
            - db
        environment:
            API_PORT: $API_PORT
            DOMAIN: $DOMAIN
            DB_URL: $DB_URL
            TOKEN_KEY: $TOKEN_KEY
            NODE_ENV: $NODE_ENV
        volumes:
            - /fossil-jackets-api/node_modules
            - ./api:/fossil-jackets-api

    app:
        build: ./app
        container_name: fossil-jackets-app
        depends_on:
            - api
        environment:
            DOMAIN: $DOMAIN
            NODE_ENV: $NODE_ENV
            REACT_NATIVE_PACKAGER_HOSTNAME: $HOST_IP
        ports:
            - 19000:19000
            - 19001:19001
        volumes:
            - /fossil-jackets-app/node_modules
            - ./app:/fossil-jackets-app

    client:
        build: ./client
        container_name: fossil-jackets-client
        depends_on:
            - api
        environment:
            DOMAIN: $DOMAIN
            PORT: $CLIENT_PORT
            NODE_ENV: $NODE_ENV
        volumes:
            - /fossil-jackets-client/node_modules
            - ./client:/fossil-jackets-client

    db:
        image: postgres:10.4-alpine
        container_name: fossil-jackets-db
        environment:
            DB_URL: $DB_URL
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            POSTGRES_DB: $POSTGRES_DB
        volumes:
            - ./db:/db

    nginx:
        build:
            context: ./nginx
            args:
                API_PORT: $API_PORT
                CLIENT_PORT: $CLIENT_PORT
                DOMAIN: $DOMAIN
        container_name: fossil-jackets-nginx
        depends_on:
            - api
            - client
        ports:
            - 443:443
        volumes:
            - ./client/build:/var/www/html
            - ./nginx/certificates:/etc/nginx/external
