version: '3'

services:
    api:
        build: ./api
        container_name: fossil-jackets-api
        depends_on:
            - db
        environment:
            API_PORT: $API_PORT
            DB_URL: $DB_URL
            JACKETS_TABLE: $JACKETS_TABLE
            USERS_TABLE: $USERS_TABLE
            NODE_ENV: development
        volumes:
            - /fossil-jackets-api/node_modules
            - ./api:/fossil-jackets-api

    db:
        image: postgres:10.4-alpine
        container_name: fossil-jackets-db
        environment:
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            POSTGRES_DB: $POSTGRES_DB
        volumes:
            - ./db:/db
